/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LabExerciseOne.src.test.java.LabExerciseOne;

import LabExerciseOne.Test;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    private void assertNotNull(String string, String greeting) {
    }
}
